# Configuração específica para Easypanel
# Sistema de Cotas - Porta 8005

version: '3.8'

services:
  sistema-cotas:
    build: .
    ports:
      - "8005:8000"  # Porta externa 8005, interna 8000
    environment:
      - DEBUG=False
      - EASYPANEL=True
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-me-in-production}
      - DATABASE_URL=sqlite:///app/db.sqlite3
      - TIME_ZONE=Europe/Lisbon
      - LANGUAGE_CODE=pt-br
      - ALLOWED_HOSTS=*
    volumes:
      - media_data:/app/media
      - logs_data:/app/logs
      - static_data:/app/staticfiles
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  media_data:
    driver: local
  logs_data:
    driver: local
  static_data:
    driver: local
